const BAD_REQUEST = 400;
const UNAUTHORIZED = 401;
const CONFLICT = 409;
const NOT_FOUND = 404;
const INTERNAL_SERVER_ERROR = 500;
const BAD_GATEWAY = 502;

module.exports = {BAD_REQUEST, BAD_GATEWAY, UNAUTHORIZED, CONFLICT, NOT_FOUND, INTERNAL_SERVER_ERROR};